# Site
repository: sproogen/resume-theme
favicon: images/atom.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Edu Maldonado Olguin
title: Analista de Datos
email: triss.maldonado@outlook.com
website: https://github.com/trissmald


# Dark Mode (true/false/never)
darkmode: true

# About Section
about_title: Acerca de mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Christopher Maldonado. Soy un apasionado de la programación, realmente me divierto escribiendo líneas de código que después no funcionan, solo bromeo. Mi área de especialidad es <mark>análisis de datos</mark>.
  El lenguaje de programación que manejo es <mark>python</mark> con librerías como <mark>pandas, numpy, matplotlib</mark> para la gestión de datos. 
  
  Dentro de las herramientas de visualización avanzada como <mark>business intelligence</mark> tengo control de <mark>Power BI y Tableau</mark>, de la misma forma que complemento mi conocimiento con herramientas y lenguajes de base de datos como lo son <mark>SQL</mark>, entre ellas he tenido experiencia con <mark>MySQL, SQLite y PL/SQL.</mark>
  
  Esperando que mis habilidades rindan al máximo en el puesto desempeñado y siempre mejorando.

content:
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Autonoma de Nuevo León
        caption: 2019 - 2023
        sub_title: Licenciado en Matemáticas
        description: Durante mi estancia en la universidad aprendí sobre modelos matemáticos, probabilidad avanzada, cálculo, algoritmos, funciones y muchas otras herramientas matemáticas que me ayudan en mi camino de convertirme en Científico de Datos.
   - title: Proyectos # Title for the section
     layout: list # Type of content section (list/text)
     content:
       - layout: left
         title: Analisis de Futbool en Ligas Europeas 
         sub_title: Utilizado Python, numpy, pandas, matplotlib.
         description: En este proyecto se pone en práctica las nociones más básicas de Python y las librerías de análisis de datos como pandas, numpy y matplotlib. Se analizaron 11 países europeos y 27 ligas de futbol donde se necesitó ocupar métodos de web scraping para obtener la información de las listas de frames que se necesitaban para completar los análisis correspondientes. Añadiendo que fue necesario analizar a conciencia la estructura de sus enlaces, una vez recabados fueron almacenados en algunas listas de frames mas grandes para poder "unificarlos" y de esa manera poder pasar a la etapa de cálculos estadísticos y de visualización. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
