# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Edu Maldonado Olguin
title: Analista de Datos
email: triss.maldonado@outlook.com
website: https://github.com/trissmald

# Dark Mode (true/false/never)
darkmode: true

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Christopher Maldonado. Soy un apasionado de la programación, realmente me divierto escribiendo líneas de código que después no funcionan, solo bromeo. Mi área de especialidad es análisis de datos, base de datos, todo con datos. Contáctame.

  Mi area de conocimiento: <mark>SQLServer, SQLite, MySQL, Python, PowerBI, Tableu</mark> and <mark>comer pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/
        # link_text: Project Website
        additional_links:
          - title:  
            icon: 
            url: 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UANL - Universidad Autonoma de Nuevo León
        caption: 2019 - 2023
        sub_title: Licenciado en Matemáticas
        description: | # this will include new lines to allow paragraphs
          Durante mi estancia en la universidad aprendí sobre modelos matemáticos, probabilidad avanzada, cálculo, algoritmos, funciones y muchas otras herramientas matemáticas que me ayudan en mi camino de convertirme en Científico de Datos.
  - title: Un poco sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Me gusta pasar tiempo en casa con amigos y mi familia, comer y cenar pizza.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
