# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Edu Maldonado Olguin
title: Analista de Datos
email: triss.maldonado@outlook.com
website: https://github.com/trissmald


# Dark Mode (true/false/never)
darkmode: true

# About Section
about_title: Acerca de mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Christopher Maldonado. Soy un apasionado de la programación, realmente me divierto escribiendo líneas de código que después no funcionan, solo bromeo. Mi área de especialidad es análisis de datos, base de datos, todo con datos. Contáctame.

  Mi area de conocimiento: <mark>SQLServer, SQLite, MySQL, Python, PowerBI, Tableu</mark> and <mark>comer pizza</mark>

content:

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UANL - Universidad Autonoma de Nuevo León
        caption: 2019 - 2023
        sub_title: Licenciado en Matemáticas
        description: | # this will include new lines to allow paragraphs
          Durante mi estancia en la universidad aprendí sobre modelos matemáticos, probabilidad avanzada, cálculo, algoritmos, funciones y muchas otras herramientas matemáticas que me ayudan en mi camino de convertirme en Científico de Datos.
  - title: Un poco sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Me gusta pasar tiempo en casa con amigos y mi familia.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
