# Site
repository: sproogen/resume-theme
favicon: images/atom.ico

# Content configuration version
version: 2

#Social Links
github_username:  trissmald

# Personal info
name: Christopher Edu Maldonado Olguin
title: Analista de Datos

# Dark Mode (true/false/never)
darkmode: true

# About Section
about_title: Acerca de mi
about_profile_image: /images/atomprofile.png
about_content: | # this will include new lines to allow paragraphs
  Soy Analista de Datos con manejo avanzado de Python, SQL, Power BI, Excel con experiencia de más de un año. Manejo librerías avanzadas para
  análisis de datos y base de datos en varios softwares. Me entusiasma aprender y mi meta profesional es convertirme en Científico de Datos, estudie
  una licenciatura en Matemáticas por lo que cuento con las herramientas de probabilidad y estadística dentro de mi área de conocimiento.
  
  Dale un vistazo a mi perfil de GitHub!

content: 
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Base de Datos en EMSA Multiservicios 
        sub_title: Admistración de base de datos con Microsoft Excel (Agosto 2020 - Febrero 2022)
        description: |
          Gestioné y administré la base de datos utilizando Microsoft Excel, garantizando la integridad, precisión y actualización de la información.
          
          Desarrollé y mantuve sistemas de seguimiento y control de inventario utilizando fórmulas y funciones avanzadas de Excel, lo que permitió una gestión eficiente del stock y una reducción de pérdidas y roturas.
          
          Diseñé y generé informes periódicos de ventas, análisis de datos y métricas clave utilizando tablas dinámicas, gráficos y otras herramientas de visualización en Excel.
  
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Analisis de Soccer en Ligas Europeas 2010/2023
        sub_title: Python, numpy, pandas, matplotlib.
        link: github.com/trissmald/EuroSoccer1023
        description: | # this will include new lines to allow paragraphs
          En este proyecto se pone en práctica las nociones más básicas de Python y las librerías de análisis de datos como pandas, numpy y matplotlib. Se analizaron 11 países europeos y 27 ligas de futbol a lo largo de 2010 a 2023 donde se necesitó ocupar métodos de web scraping para obtener la información de las listas de frames que se necesitaban para completar los análisis correspondientes.
          
          Añadiendo que fue necesario analizar a conciencia la estructura de sus enlaces, una vez recabados fueron almacenados en algunas listas de frames mas grandes para poder "unificarlos" y de esa manera poder pasar a la etapa de cálculos estadísticos y de visualización. 

  - title: Power BI # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-center
        title: Atentos Call Center Report
        sub_title: KPIS
        link: https://acortar.link/4nS0wd
        description: |
          <div align="center">
          <iframe title="Reporte (test_prueba) - Atentos Abril 2023" width="1024" height="612" src="https://app.powerbi.com/view?r=eyJrIjoiMmIyYzk3MzctYmQxZS00NjQ0LWFhMGQtOWI5MTRlY2UzOGMxIiwidCI6ImNhY2E5MDExLTdiNmEtNDRkZS04NjFmLTA5NWEyY2E4ODNiNyIsImMiOjR9&pageName=ReportSection" frameborder="0" allowFullScreen="true"></iframe>
          <div align="center">
  
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Autonoma de Nuevo León
        caption: 2020 - 2024
        sub_title: Licenciado en Matemáticas
        description: |
          Durante mi estancia en la universidad aprendí sobre modelos matemáticos, probabilidad avanzada, cálculo, algoritmos, funciones y muchas otras herramientas matemáticas que me ayudan en mi camino de convertirme en Científico de Datos.
  
  - title: Increible Arte
    layout: text
    content: | # this will include new lines to allow paragraphs 
      ![imagen](/presentacion/images/landscape.JPG "Village Japanese")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
